### ISSUE TITLE
Suche der gewünschten Informationen

### ISSUE THREAD

**Issue by bittejus** [BergerHM/testchat#7]
Um gewünschte Infos aus Confluence zu bekommen, muss geklärt werden wie man nach etwas spezielles sucht durch die Eingabe in den chatbot.

Vllt. kann man die Suche in Confluence anzapfen, die Eingabe des chatbots übermitteln und das Suchergebnis mithilfe des chatbots wieder ausgeben....

**Comment by oldenstreeter** [comment]
Confluence API wurde erfolgreich erforscht
